## Intro to Python

In this lab you will be familiarizing yourself with the programming language called Python. Python is a so-called high level programming language. Which means it is very abstracted from machine languages and are easily readable by humans. 

Python is one of the most popular programming languages nowadays, and is used in various spheres from research and Data Science to Machine Learning and Artificial Intelligence.

In this lab you will also learn some of the most popular Python libraries such as Pandas, Numpy, and Matplotlib. Libraries are used to make Python more efficient. By itself (solely with built-in functions and methods), Python is not a very useful language, hence people keep building libraries (sets of functions and methods) that can be used together with Python in order to make it more useful.

### 1. Python's Data Types 

#### 1.1 Numerals

One of the data types that is commonly used in Python are numerals (aka numbers). 
With numerals, Python can be used as a calculator. Run the cells below to see it for yourself.

In [8]:
3+5

8

In [9]:
140-20

120

In [10]:
40/2

20.0

In [73]:
2*2

4

Python follows the same arithmetic rules as we do. So guess what the output of the next cell will be:

In [75]:
2*5+1

11

What about this cell:

In [79]:
2*(5+1)

12

Guess what a double star notation does? Run the cell below to see if you had the right intuition about it.

In [80]:
3**2

9

There are a few types of them: integers and floats. 
They are not compatible, so it is important to remember which one you are using in order to avoid bugs. Floats use decimal points, so it will be easy for you to spot them. See how the output changes when we print the same number as an integer and as a float.

In [56]:
int(1776)

1776

In [57]:
float(1776)

1776.0

#### 1.2 Strings

The phrases and words in Python are always stored inbetween double or single quotation marks. They are formally called strings.

In [25]:
"History has its eyes on you"

'History has its eyes on you'

The strings can also be "added" onto one another. Run the cell below to see how it works.

In [24]:
"York"+"town"

'Yorktown'

To store the values in Python (and in many other programming languages) we need to use variables. Variables can store all kinds of information. This is useful if you plan to use the same values later on in your project. It will save you time and make your code more readable. To see how we store values in variables run the cell below.

In [27]:
burr = "Wait for it!"
burr

'Wait for it!'

A string is a sequence of characters. If you want to see how many characters your string has, use the len() method. Do you think spaces are considered characters in Python? Check if your intuition was correct by running the cell below.

In [29]:
len(burr)

12

Now create a variable name in which you will save your full name. Note that you need to call the variable once again in order to get an output.

In [19]:
# name = "Alexander Hamilton"
# name

Sometimes you need to switch the values in two variables. 
In the cell below we have the last names mixed up. The variable theodosia should have an output "burr" and philip should return "hamilton".
How would you approach this problem without manually retyping the outputs?

**Hint** Use a temporary variable in which you can temporarily save the value of one of the other variables. 

In [26]:
theodosia = "hamilton"
philip = "burr"


# temp = theodosia
# theodosia = philip
# philip = temp

#### 1.3 Lists

You have learnt about the strings and numerals, it's time to take it up a notch. Another useful and very popular data type is a Python list.
Lists can take various data types (both numerals, strings, arrays, other lists, etc). 

To create an empty list just make your variable equal to "[ ]", like so:

In [99]:
washington = []
washington

[]

To add the values into your list you can either use lst.append( ), lst.insert( ), or lst.extend( ).

In [100]:
washington.append("Right Hand Man")
washington

['Right Hand Man']

In [101]:
washington.insert(0, "I need my")
washington

['I need my', 'Right Hand Man']

In [102]:
washington.extend(["Back"])
washington

['I need my', 'Right Hand Man', 'Back']

Notice, that the insert method takes two positional values. You need to specify the index in the list at which it will be inserted, whilst append just adds the value to the end of the list. 
extend takes another list as its input. If you try to use a string or a number by itself, it will give you an error.

When you need to access an element at a specific index, that is the code you can use:

In [103]:
washington[1]

'Right Hand Man'

**Note:** Python starts counting at 0, not 1.

Sometimes you just need to use part of the list. In this case you can use ":" to modify your list. Let's make a new list:

In [93]:
lyrics = ["I", "am", "not", "throwing", "away", "my", "shot"]
lyrics

['I', 'am', 'not', 'throwing', 'away', 'my', 'shot']

Let's say you want to save only the two last words from your old list into your new list. That's what you will need to do then:

In [94]:
alex = lyrics[5:]
alex

['my', 'shot']

Notice also that if you want to learn the length of your list, you can use the same method "len( )", but it will not count all the characters anymore. Instead, it will count all the elements in it. Like so:

In [132]:
len(washington)

3

### 2. Built-in Functions

Although Python doesn't have a lot of functions and methods by itself, it is not like it doesn't have any. Let's go over some of the most valuable built-in funsctions in Python.

In [133]:
min(1, 3)

1

In [134]:
max(15, 25, 70)

70

You can also use these functions with strings. Can you guess what the output will be?

In [135]:
max("Hamilton", "Washington")

'Washington'

So does Python know that George Washington was older than Alexander Hamilton? Of course not, when comparing strings, Python goes of off the letters of alphabet. Since "W" goes after "H" in the alphabet, "Washington" is a value that is "bigger" than "Hamilton".

Another valuable function you can use with your numerals is "round". It will round your floats to the nearest integer. Like so:

In [136]:
round(8.7)

9

Another useful function we can use with numbers is "abs". It outputs an absolute value of a number:

In [137]:
abs(-3.5)

3.5

### 3. Conditionals and For-loops

#### 3.1 Conditionals

Conditionals are also known as **booleans**. With conditional statements we can let the computer know when (aka under which condition) we want a specific operation to be executed. Under the hood the computer evaluates if the condition is True and performs a specific operation (like print( ), return( ), etc). Some of the most popular conditional statements are:

**A == B: True if A equals B**

**A != B: True if A is not equal to B**

**A > B: True if A is greater than B. Same syntax for "<"**

**A >= B: True if A is greater than or equal to B. Same syntax for "<="**

In the cell below guess what the output will be, before you run it. Feel free to change the numeral under the variable "year".

In [105]:
year = 1790

if year>=1789 and year<=1787:
    print("George Washington")
elif year>=1787:
    print("John Adams")
else:
    print("King George")

John Adams


We can also search through lists of values in our conditional statements:

In [111]:
founding_fathers = ["Jefferson", "Hancock", "Hamilton", "Adams", "Washington", "Burr", "Madison"]

if "any_name" in founding_fathers:
    print("You are not throwing away your shot!")
else:
    print("You've got to be in the room where it happens!")

You've got to be in the room where it happens!


#### 3.2 Loops

Loops (aka for-loops) allow for some code to be executed repeatedly. For example, if you wish to print the numbers from 0 to 10, you can do that with the for-loop. 

**Note:** remember that Python starts to count from 0, hence the last number you specify is not going to be included.

In [121]:
for i in range(11):   
    print(i)

0
1
2
3
4
5
6
7
8
9
10


We can make our for-loops more complicated by including both enumeration (counting) and iteration through a list. You can see an example of it below:

In [127]:
presidents = ["George Washington", "John Adams", "Thomas Jefferson", "James Madison", "James Monroe"]

for num, name in enumerate(presidents, start=1):
    print("The U.S. President #", num, "was", name)

The U.S. President # 1 was George Washington
The U.S. President # 2 was John Adams
The U.S. President # 3 was Thomas Jefferson
The U.S. President # 4 was James Madison
The U.S. President # 5 was James Monroe


### 4. Working with Libraries

It is time for us to introduce a concept of Python libraries. As we mentioned before, Python is not a very powerful programming language by itself. What makes it powerful are the libraries people wrote for it. Libraries are the sets of different functions that you can import and use. The two most popular libraries are numpy and pandas.


Since we are using anaconda, a lot of libraries have been preloaded for you. You just need to "call" them. Just run the cell below. It will make our notebook know that we will be using these preinstalled libraries from that point on. 

In [53]:
import pandas as pd
import numpy as np

With the help of numpy we can introduce a new data type - arrays. Arrays are commonly used with Data Frames (basically, tables of values). There are a lot of functions and methods that can be used with arrays when one is analysing their data. The main difference between the lists and arrays is that an array can take only one type of data (eg. only numerals, or strings, but never both).

To create an array with values, just make your variable equal to np.array("your value")

In [69]:
arr = np.array(10)
arr

array(10)

A very useful method that can be used with an array of numbers is np.arange( ). It takes at least 2, sometimes 3 positional arguments. The first number will be the starting point of your array, the last one will identify up to which number your array will go (not inclusive). The third positional argument is optional, it shows how many steps an array should skip through. 

For example, if you need an array with numbers from 0 to 20, but you only want for it to include every other number, you will need add a thrird positional argument.

In [72]:
every_other = np.arange(0, 21, 2)
every_other

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

You can also convert a list of numbers in Python into an array:

In [129]:
num_lst = [1, 2, 3, 4, 5]
num_arr = np.array(num_lst)
num_arr

array([1, 2, 3, 4, 5])

You can do some arithmetic with arrays. Guess what will be the output of this line of code before your un it:

In [130]:
num_arr*2

array([ 2,  4,  6,  8, 10])

Try performing the same operation with the initial list of numbers. What do you think the output will be?

In [131]:
num_lst*2

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

As you can see, lists and arrays cannot only be used differently, but they also give different outputs when we are using the same operations on them.

### 5. Data Frames and Tables

In [115]:
broadway = pd.read_csv("broadway.csv")
broadway.head(7)

,Attendance,Capacity,Day,Full,Gross,Gross Potential,Month,Name,Performances,Theatre,Type,Year
0,5500,88,26,08/26/1990,134456,0,8,Tru,8,Booth,Play,1990
1,1737,100,24,03/24/1991,100647,0,3,Miss Saigon,0,Broadway,Musical,1991
2,12160,100,31,03/31/1991,634424,0,3,Miss Saigon,0,Broadway,Musical,1991
3,13921,100,7,04/07/1991,713353,0,4,Miss Saigon,0,Broadway,Musical,1991
4,10973,90,14,04/14/1991,573981,0,4,Miss Saigon,4,Broadway,Musical,1991
5,14076,101,21,04/21/1991,706793,0,4,Miss Saigon,8,Broadway,Musical,1991
6,14065,101,28,04/28/1991,714968,0,4,Miss Saigon,8,Broadway,Musical,1991
